### ISSUE TITLE
2018 edition requires adding xml-rs and log dependencies

### ISSUE THREAD

**Issue by steven-joruk** [media-io/yaserde#22]
I'm using 1.37 stable with 2018 edition enabled, and I found I needed to add the `xml-rs` and `log` dependencies in order to fix some build issues. This may just be my own misunderstanding of how rust dependencies work.

```toml
[package]
name = "minimum-yaserde"
version = "0.1.0"
authors = ["Me"]
edition = "2018"

[dependencies]
yaserde = "0.3"
yaserde_derive = "0.3"

# I wouldn't expect to have to add these myself
xml-rs = ""
log = ""
```

Without adding xml-rs as a dependency:
```
src/main.rs|6 col 10 error 433| failed to resolve: could not find `xml` in `{{root}}`
||   |
|| 6 | #[derive(YaDeserialize, Debug)]
||   |          ^^^^^^^^^^^^^ could not find `xml` in `{{root}}`
src/main.rs|6 col 10 error 433| failed to resolve: use of undeclared type or module `XmlEvent`
||   |
|| 6 | #[derive(YaDeserialize, Debug)]
||   |          ^^^^^^^^^^^^^ use of undeclared type or module `XmlEvent`
```

Without adding log as a dependency:
```
src/main.rs|5 col 10 error| cannot find macro `debug!` in this scope
||   |
|| 5 | #[derive(YaDeserialize, Debug)]
||   |          ^^^^^^^^^^^^^
```
